---
    - hosts: all

      vars:
        ansible_user: ubuntu
        ansible_ssh_private_key_file: /etc/awsubuntuec2.pem

      tasks:
      - name: install nginx
        become: yes
        package:
          name:
            - nginx
          state: latest
      - name: copy index.html
        become: yes
        copy:
          src: index.html
          dest: /usr/share/nginx/html/index.html
      - name: start nginx service
        become: yes
        service: 
          name: nginx
          state: started
