# Error when tring to remote to Amazon EC2 server. Will try Azure server when i have timezonefatal: [13.210.79.31]: UNREACHABLE! => {
#     "changed": false,
#     "msg": "ntlm: HTTPSConnectionPool(host='13.210.79.31', port=5986): Max retries exceeded with url: /wsman (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f43db63b438>: Failed to establish a new connection: [Errno 111] Connection refused',))",
#     "unreachable": true
# }
---
  - hosts: all
    vars:
      ansible_user: Administrator
      ansible_password: T6Kewued8-w?oE6a2KOu&=Tv).zoji??
      ansible_winrm_operation_timeout_sec: 100
      ansible_winrm_read_timeout_sec: 120
      ansible_connection: winrm
      ansible_winrm_transport: ntlm
      ansible_winrm_server_cert_validation: ignore

    tasks:
    - name: Install IIS
      win_feature:
          name: web-server
          include_management_tools: yes
          include_sub_features: yes
          state: present 

    - name: Copy index.html to wwwroot
      win_copy:
        src: index_html
        dest: C:\inetpub\wwwroot\index.html
        force: yes
    
    - name: Create logs directory
      win_file: 
        path: C:\logs
        state: directory

    - name: install net core iis hossting module with no frameworks
      win_chocolatey:
        name: "dotnetcore_windowshosting"
        version: "3.1.0"
        install_args: "OPT_NO_RUNTIME=1 OPT_NO_SHAREDFX=1 OPT_NO_X86=1 OPT_NO_SHARED_CONFIG_CHECK=1"
        state: present
        notify: restart IIS
    
    handlers:
      - name: restart IIS
        win_shell: '& {iireset}'